#include<vector>
#include<iostream>

//This file accepts a (single? list of?) vertex lists and face lists, generated by read_off.cpp, and converts them into a voxel 
//object of a given resolution. In our case, a 32x32x32 grid of binary values (1s and 0s), represented as a 3d vector.

void main()
{
	//vector<vector<vector<int>>> obj; 
	return 0;
}